name: CI/CD

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: pcandido/ecoleta
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: npm ci
    - run: npm run build

    - name: Upload dist
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download dist
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist

    - name: Build image
      run: docker build -t $IMAGE_NAME .

    - name: Log into registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - run: docker push $IMAGE_NAME
